from cx_Freeze import setup, Executable

setup(
    name="Обработчик географических данных",
    version="1.0",
    description="Обработчик географических данных",
    executables=[Executable("ui_mode_app2.py")],
    options={
        "build_exe": {
            "packages": [
                "tkinter",
                "altgraph",
                "cabarchive",
                "certifi",
                "cffi",
                "DateTime",
                "deep_translator",
                "future",
                "geographiclib",
                "geopy",
                "gevent",
                "greenlet",
                "h3",
                "idna",
                "lief",
                "numpy",
                "packaging",
                "pandas",
                "pefile",
                "pycparser",
                "pyparsing",
                "pytz",
                "requests",
                "setuptools",
                "six",
                "soupsieve",
                "striprtf",
                "timezonefinder",
                "tomli",
                "typing_extensions",
                "tzdata",
                "urllib3",
                "zope.event",
                "zope.interface",
                "openpyxl",
            ],
        }
    },
)
